### PR TITLE
Fix NameError in generated modules

### PR DESCRIPTION
**Pull request by junkmd**
https://github.com/enthought/comtypes/issues/284#issuecomment-1071665989

Fix broken imports of generated modules.

### CODE REVIEW

**Comment by junkmd** [comment]
fix comments.

**Comment by junkmd** [comment]
> @junkmd Does this also fix the ```c_float``` [issue](https://github.com/enthought/comtypes/issues/284#issuecomment-1061466526)

@PhilippSelenium 
Yes it does.
This adds `from ctypes import *` line to modules under `comtypes/gen/…`.

**Comment by psisquared2** [comment]
Thank you for the pull request. I had the `c_int` and `c_float` problems with `portabledeviceapi.dll` and `portabledevicetypes.dll` in both 1.1.11 and 1.1.12, which got fixed by this patch.

**Comment by junkmd** [comment]
@psisquared2
(cc: @PhilippSelenium )

You're welcome.
I found another problem in generated module namespaces. (#293)

I will submit another PR that fixes both #284 and #293.

If this PR was not merged until I submit new PR, I will close this and write comment to guide to new PR.

**Comment by junkmd** [comment]
Please see #294

**Pull request closed without merging**
