### PR TITLE
Solution to IndexError for empty SafeArrays

### PR DESCRIPTION
**Pull request by BALOGHBence**
#247

### CODE REVIEW

**Comment by vasily-v-ryabov** [comment]
Moved your changes to PR #259 . Some testing is welcome.

**Comment by vasily-v-ryabov** [comment]
This solution causes problems in case `numpy` is not installed and not needed. Scroll down to the very bottom here:
https://ci.appveyor.com/project/pywinauto/pywinauto-8b7t7/builds/42465094/job/0hm3n1w13k33fd2j

I'm going to revert this "fix" for release 1.1.11. Any better fix is welcome.

**Comment by vasily-v-ryabov** [comment]
Sorry, the problem was not in your fix. I will probably keep your changes if tests are OK.

**Comment by BALOGHBence** [comment]
Thank you Vasily!

**Pull request closed without merging**
