### PR TITLE
[WIP] Passing tests with AppVeyor CI

### PR DESCRIPTION
**Pull request by junkmd**
**WIP: To comfirm AppVeyor CI, I'm doing code->test-with-appveyor-by-pushing->code-some-more loop.**
**I will close this PR and re-submit new one when I finished fixing code.**

This PR has taken over from #271 by @dmwyatt
(and trial #278 by @kdschlosser)

Formerly, [Appveyor CI on `comtypes` is very limited that only 2 install test](https://github.com/enthought/comtypes/pull/294#discussion_r884285454).

This makes test suite runnable with AppVeyor CI and adds workaround for minimum testing.
- The failed test cases with AppVeyor CI were skipped or repair.
- The tests that dependent upon IE and MS Office were skipped.

## Added codes to rebased @dmwyatt branch
- Add `unittest.skipUnless` to the test that was failed in 32bit Python.
- Fix condition branch for `reload`.

## The remaining tasks
- Build a better test suite.
- Find any non-environment-specific COM library to replace some used by the skipped test.(`Need to use something built-in to Windows for sure.`)
- Fix test case that was failed in only 32bit Python.

### CODE REVIEW

**Comment by junkmd** [comment]
For making test suite code more clean, I converted this PR draft.

**Comment by vasily-v-ryabov** [comment]
This is the way to indicate number of tests on summary AppVeyor page: https://github.com/pywinauto/pywinauto/commit/62e869b0879a158f9bc981b63139b6db034ff9aa

It would look like this: https://ci.appveyor.com/project/pywinauto/pywinauto/builds/43748313

**Comment by vasily-v-ryabov** [comment]
+ one more modification to use AppVeyor BUILD_ID etc: https://github.com/pywinauto/pywinauto/commit/c45dece861e823651273a8d8504d60c73b32dd78

**Comment by junkmd** [comment]
@vasily-v-ryabov 

Frankly speaking, at this phase, is it necessary to show the number of tests on the AppVeyor summary page?

We can still see the test results from the `console` page as of now.

I think top priority is skipping the environment-specific-tests to enable AppVeyor CI to run **minimum** testing.

**Comment by junkmd** [comment]
I found `ResourceWarning` in `test_pip_install.py`.
```
...
test_pip_install.py:15: ResourceWarning: unclosed file <_io.TextIOWrapper name='comtypes/__init__.py' mode='r' encoding='cp1252'>
  return value.strip().strip('"').strip("'")
...
```
To prevent appearing this warning, using `IOBase` context manager.
- before
https://github.com/enthought/comtypes/blob/2a59544d7b174bd3f90e01776955eb2e33c95583/test_pip_install.py#L12-L15

- after
https://github.com/enthought/comtypes/blob/8801581fc03a6a32ae413cf2e0e98d4b7ec711fd/test_pip_install.py#L12-L16

**Comment by junkmd** [comment]
AppVeyor CI was failed in `test_LoadTypeLibEx` with 32bit environments.
- https://github.com/enthought/comtypes/blob/0e818a6b01d103eeedfba9194dfb30db77282325/comtypes/test/test_typeinfo.py#L31-L34

And this test has a conditional branch for environments.
- https://github.com/enthought/comtypes/blob/0e818a6b01d103eeedfba9194dfb30db77282325/comtypes/test/test_typeinfo.py#L14-L19

`test_LoadTypeLibEx` problem was reported(#40) a long time ago (in 2014), but it is not resolved.

As a compromise, 

- using attribute value assert instead of object assert.

  - https://github.com/enthought/comtypes/blob/bedbfc05b4c78227c84cdea63463250f2a199775/comtypes/test/test_typeinfo.py#L26-L36
- using non-environment-specific dll.
  - https://github.com/enthought/comtypes/blob/bedbfc05b4c78227c84cdea63463250f2a199775/comtypes/test/test_typeinfo.py#L15

**Comment by junkmd** [comment]
`test_typeinfo.py` is failed in python 3.3.

`import.reload` is `New in version 3.4`.
https://docs.python.org/3.5/library/importlib.html#importlib.reload
https://github.com/enthought/comtypes/blob/08eb696f40f3aa4201fb8af736a2ee0f2b0fda73/comtypes/test/test_findgendir.py#L11-L14

To python 3.3-compatible, using `from imp import reload`.
https://docs.python.org/3/library/imp.html#module-imp
```py
if sys.version_info >= (3, 4):
    from importlib import reload
else:
    from imp import reload
```

**Comment by junkmd** [comment]
see #298

**Pull request closed without merging**
