### PR TITLE
Fixes TypeError when wrapping `esriSystem.olb`

### PR DESCRIPTION
**Pull request by maphew**
More details at http://gis.stackexchange.com/questions/37672/arcobjects-comtypes-at-10-1. Comtypes is the most popular route to using the Esri ArcObjects com library for functions that are not exposed in the official ArcPy library.

### CODE REVIEW

**Comment by cfarrow** [comment]
Thank you for the patch. I am looking for a way to write a test for this before merging the change into the codebase. I always prefer writing tests against freely available libraries so there is little overhead to running the tests. I'll look at alternative options if this turns out to be infeasible.

**Comment by maphew** [comment]
Thanks for considering it. I'm happy to run tests you or anyone else could provide against my environment and share the results. Unfortunately I'm near clueless how to write proper tests for something like this myself.

**Comment by cfarrow** [comment]
Sorry for the long delay. I've determined that this will do good without harm. I have been able to write a simple test, so I'm merging it. Thanks!

**Comment by maphew** [comment]
Oh this is wonderful, thank you!

Matt

**Comment by cfarrow** [comment]
I meant to say _unable_ to write a simple test. Nonetheless, I understand the patch and it will break anything. Thanks again.

**Comment by markkness** [comment]
And I think you mean it will NOT break anything :)

**Comment by cfarrow** [comment]
This is what happens when I try to do important things on the weekend. :D

**Pull request merged**
