### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by denfromufa**

### CODE REVIEW

**Comment by cfarrow** [comment]
Thanks for this. I'll take a look and test it out as soon as I find some time.

**Comment by denfromufa** [comment]
Actually @eryksun has a better solution which I tested yesterday:

http://pastebin.com/SQN4gqZ0

**Comment by denfromufa** [comment]
```
if outnum == 1: # rescode is not iterable
    if len(outargs) == 1:
        rescode = rescode.__ctypes_from_outparam__()
    return rescode
```

**Comment by cfarrow** [comment]
Superseded by #113.

**Pull request closed without merging**
