### PR TITLE
quit using `Generator._externals`, use `Generator.imports`

### PR DESCRIPTION
**Pull request by junkmd**
`Generator._externals` was used to avoid duplicated-calling `comtypes.client.GetModule`.

`Generator.imports` is used to  avoid duplicated-writing `import comtypes.gen._...` line in generated modules.

Their roles were similar.

With this change, to simplify `Generator.External` code, `__contains__` is added to `ImportedNamespaces`, and use `if modname not in self.imports` instead of `if libdesc in self._externals`.

### CODE REVIEW

**Review by vasily-v-ryabov — APPROVED** [review]

**Comment by vasily-v-ryabov** [comment]
Thanks for all your activity! I'll be mostly offline next 2 weeks. When I'm back, I will review & merge everything that looks good and then will do a release.

**Comment by junkmd** [comment]
@vasily-v-ryabov 
Thank you for your collaboration!

> I'll be mostly offline next 2 weeks. When I'm back, I will review & merge everything that looks good and then will do a release.

I understood.

I plan to do some feature additions, code refactoring, and test restoration during those two weeks.

**Comment by junkmd** [comment]
@vasily-v-ryabov 

Are you still busy at work?

I would like to know if there are any changes to your release plan.

Please take good care of yourself.

**Comment by vasily-v-ryabov** [comment]
Sorry, I was working remotely for 3 weeks (in addition to 2 weeks vacation) and I had no chance to get back to comtypes. I'm going to review all PRs during today and next 1-2 weeks. So it can be released.

**Comment by junkmd** [comment]
@vasily-v-ryabov 

Welcome back!
I hope you had a nice vacation.

While you were absent, I read the source code of `comtypes` and submitted an issue with features that I would like to add and problems that I would like to solve.

Please keep your collaboration.

**Pull request merged**
