### PR TITLE
Fix enthought/comtypes#90

### PR DESCRIPTION
**Pull request by jakogut**

### CODE REVIEW

**Comment by cfarrow** [comment]
Thanks for the fix. This only works in python3. Can you provide a python2 solution as well?

**Comment by junkmd** [comment]
@jakogut 

Are you still interested in this?

**Comment by junkmd** [comment]
@jakogut 
@cfarrow 

Due to no recent activity, I close this.
If you wish to add this feature, please rebase, resolve conflicts and re-open or submit a new PR.

**Comment by vasily-v-ryabov** [comment]
@junkmd are we going to cherry-pick this fix to `drop-py2` branch? I think it is useful.

**Comment by junkmd** [comment]
@vasily-v-ryabov 

> @junkmd are we going to cherry-pick this fix to `drop-py2` branch? I think it is useful.

Yes, I agree.

I think we need a testcase to reproduce #90 error occurrence and validate that it can be resolved this way.

**Pull request closed without merging**
