### PR TITLE
Deleted __cmp__() functions from repository

### PR DESCRIPTION
**Pull request by alexcalvo9**
Here I deleted the out of data __cmp__() functions in comtypes as stated in issue #512 as it is no longer supported

### CODE REVIEW

**Comment by junkmd** [comment]
Hi,

Why was this closed?
I think this pull request is helpful to the project.

**Comment by alexcalvo9** [comment]
Hi Jun,

Sorry I had a project for a class where I had to complete a task for an open-source project. I didn't want to mess up anything with the project and I didn't get a chance to test out the software to make sure nothing was affected by removing the functions so I figured I would keep it on my own fork. I had to create a pull request to my own fork but accidentally created one to the main comptypes repo so that's why I closed it. If you would like me to, I can open it back up! I did two of the "good first tasks" where it was asked to delete some outdated functions

-Alexander Calvo
________________________________

**Comment by junkmd** [comment]
Hi,

Thank you for showing interest in this project.

The issue labeled as "good first issue" is based on the assumption that addressing it won't likely have a significant impact on the overall project, as mentioned in the issue description.

As stated in the issue, `__cmp__` and `cmp` belong to the older world of Python and are no longer in use. Projects explicitly implementing cmp in Python 3.7 or later are probably rare. If such projects exist, I would suggest to them to use `__eq__` instead.

Therefore, there's likely no need to worry about the proposed changes adversely affecting the project. 

Your contributions are welcome. For areas that you may not understand, I trust that the community will provide assistance.

And I hope that this project proves to be helpful for you in obtaining credits.

**Comment by alexcalvo9** [comment]
Alright then, I can open them back up. I will keep that in mind in case I try and tackle any other task! Thanks so much.
________________________________

**Pull request closed without merging**
