### PR TITLE
Fixes tools.codegenerator.Generator.generate_code

### PR DESCRIPTION
**Pull request by kdschlosser**
I ran across an issue where I had exported a typelib resource from a dll file and the resulting tlb file when fed into the code generator would fail because of a version mismatch. This was happening because the file stored in the typelib was different from the file that was being used to generate the code.

### CODE REVIEW

**Comment by vasily-v-ryabov** [comment]
@fusentasticus @dmwyatt could you please test these changes on your cases? If it works, I will merge it.

**Comment by dmwyatt** [comment]
It works for me.

**Comment by kdschlosser** [comment]
There is no rush on this. It  was something I stumbled upon when writing #274

There is also another big that I will be making a PR for but instead of just fixing that single bug I am going to eliminate any other possible bugs. It has to deal with the code generator as well but specifically the adding of non ctypes objects to a list of known ctypes objects. If that makes any sense to ya then you will kind of understand what I am getting at.

**Comment by vasily-v-ryabov** [comment]
Looks like this PR should be rebased to resolve conflicts.

**Comment by kdschlosser** [comment]
I messed up the rebase and I created a new PS to keep the commit history clean. The new PR is #281

**Pull request closed without merging**
