### PR TITLE
fix `__next__()` in IEnum code generator

### PR DESCRIPTION
**Pull request by jonschz**
This fixes https://github.com/enthought/comtypes/issues/353, see the discussion there.

### CODE REVIEW

**Comment by jonschz** [comment]
@junkmd Do you want me to add the test case here as well?

**Comment by junkmd** [comment]
@jonschz 

As a matter of fact, I want a test to ensure that a derived class of `IUnknown` which has name starts with `IEnum` and has methods named "Next", "Skip", "Reset", and "Clone" behaves as an `Iterator`.
This behavior has never been tested before.

However, for the following reasons, changing only this one line should be sufficient for the scope of this PR.

1. Before the change, it was clearly a dead code and the cause of the error in Py3.
2. This does not reduce coverage rate. Appveyor CI does not measure coverage, but I do it in my development environment. This change is a one-line-to-one-line and not adding conditional branches.
3. The discussion in #353 allows us to verify that it behaves as an `Iterator`.
The test code illustrated in #353 will only work if a portable device is connected to the environment.
There are other test cases in this package that are environment-dependent and in some cases do not run, but I want to make as few as possible in the test cases we will create.
It seems to me that there may be other COM objects that are less environment-dependent that would be more suitable than `IEnumPortableDeviceObjectIDs` for `IEnum…` is to be used for the purpose of ensuring its behavior as an `Iterator`.
But I don't know of any such COM object or COM library, so I posted #468 as `help wanted`.

**Comment by junkmd** [comment]
CIs are passed.

<details>
<summary>memo</summary>

https://github.com/enthought/comtypes/actions/runs/3914292684/jobs/6694488613
https://ci.appveyor.com/project/cfarrow/comtypes/builds/45934073
https://ci.appveyor.com/project/pywinauto/pywinauto/builds/45936118
</details>

**Review by junkmd — APPROVED** [review]
Thank you!

**Pull request merged**
